### PR TITLE
Fix rendered tab width when there are double-width characters in front

### PR DESCRIPTION
**Pull request by inkarkat**
Hello Dave,

you haven't been active in GitHub for the past two years; I hope this finds you well and you're still maintaining your nice tools.

I've been a silent occasional user of `nowrap`, and just recently found additional use cases for it. During coding, I found this bug in the existing code (and also an omitted test `tc6`).

### CODE REVIEW

**Comment by goodell** [comment]
Hi Ingo, I'm delighted to hear `nowrap` is useful to you. I'm a daily user of a number of your vim plugins, especially ConflictMotions and ConflictDetection.

I put most of my coding effort into work these days, but always happy to receive a useful PR. This contribution might finally shame me into setting up Travis CI for this little repo too (which didn't exist when I first published it).

After mostly resurrecting the fatpacker env on my current laptop and without even incorporating your patches, I get failures in `tc5` and `tc7` related to Thai combining characters. Looks like I both haven't properly updated the copy of `Text::CharWidth:PurePerl` in this git repo and probably also have some obsolete fatpacker incantation. I'll spend a little time this week to debug that and clean things up in general so that I can test, pull, and release these PRs properly.

**Comment by inkarkat** [comment]
Ah, I'm so glad you haven't abandoned this project; this unfortunately happens all too often.

>  I get failures in tc5 and tc7 related to Thai combining characters

Yes, I've encountered those as well, but I attributed that to a mistake on my side; I had to install the fatpacker dependency, too, and all of that was new to me. Having a CI build where one could see how it's supposed to be built would indeed help here. I then worked around the issue by directly invoking the original source script:

    $ PERLLIB=../fatlib NOWRAP=../script/nowrap.pl make

I feel a little bit bad that these PRs have surfaced some hidden debt and action items for you; take your time and work on it whenever it suits you; I don't mind at all if these PRs stay open for quite some time!

**Comment by goodell** [comment]
Manually merged via CLI to make sure the fat-packed `nowrap` script got properly updated. Thanks again for the PRs.

**Comment by goodell** [comment]
Also, builds have been cleaned up and the project now builds automatically under Travis: https://travis-ci.org/goodell/nowrap

**Pull request merged**
